# Generated by Django 4.0.7 on 2023-04-26 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_completed_task_iscompleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='iscompleted',
            new_name='completed',
        ),
    ]
